Updates

diff --git a/vim/bootstrap b/vim/bootstrap
--- a/vim/bootstrap
+++ b/vim/bootstrap
@@ -1,5 +1,15 @@
 #!/bin/bash
 base=$(dirname $0)
+
+gettheme() {
+    echo "Getting lucius color theme..." && \
+    cd $HOME/.vim && git clone https://github.com/jonathanfilip/vim-lucius && \
+    cp -ir vim-lucius/colors .
+    rm -rf vim-lucius
+}
+
+gettheme
+
 git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
 if [ -e $HOME/.vimrc ]; then
     read -p ".vimrc exists. Overwrite? [y/N] " yn
@@ -7,11 +17,16 @@ if [ -e $HOME/.vimrc ]; then
         [Yy]* )
             cp $HOME/.vimrc $HOME/vimrc.bak
             cp $base/vimrc $HOME/.vimrc && echo "Created backup $HOME/vimrc.bak"
+            gettheme
             ;;
-        * ) echo "Aborting" && exit ;;
+        * )
+            echo "Aborting"
+            exit 1
+            ;;
     esac
 else
     cp $base/vimrc $HOME/.vimrc && echo ".vimrc copied"
 fi
 
 vim +BundleInstall +qall && echo ".vimrc is now set up with vundle plugins"
+
